language: ruby

rvm:
  - 2.0.0

services:
  - mongodb

before_script: 
  - cp config/mongoid.example.yml config/mongoid.yml

# use default Travis test suite kick off
# http://about.travis-ci.org/docs/user/languages/ruby/#Default-Test-Script
# 
# script: bundle exec rake
