require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BridgesController do

  # This should return the minimal set of attributes required to create a valid
  # Bridge. As you add validations to Bridge, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "content" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BridgesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all bridges as @bridges" do
      bridge = Bridge.create! valid_attributes
      get :index, {}, valid_session
      assigns(:bridges).should eq([bridge])
    end
  end

  describe "GET show" do
    it "assigns the requested bridge as @bridge" do
      bridge = Bridge.create! valid_attributes
      get :show, {:id => bridge.to_param}, valid_session
      assigns(:bridge).should eq(bridge)
    end
  end

  describe "GET new" do
    it "assigns a new bridge as @bridge" do
      get :new, {}, valid_session
      assigns(:bridge).should be_a_new(Bridge)
    end
  end

  describe "GET edit" do
    it "assigns the requested bridge as @bridge" do
      bridge = Bridge.create! valid_attributes
      get :edit, {:id => bridge.to_param}, valid_session
      assigns(:bridge).should eq(bridge)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Bridge" do
        expect {
          post :create, {:bridge => valid_attributes}, valid_session
        }.to change(Bridge, :count).by(1)
      end

      it "assigns a newly created bridge as @bridge" do
        post :create, {:bridge => valid_attributes}, valid_session
        assigns(:bridge).should be_a(Bridge)
        assigns(:bridge).should be_persisted
      end

      it "redirects to the created bridge" do
        post :create, {:bridge => valid_attributes}, valid_session
        response.should redirect_to(Bridge.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bridge as @bridge" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bridge.any_instance.stub(:save).and_return(false)
        post :create, {:bridge => { "content" => "invalid value" }}, valid_session
        assigns(:bridge).should be_a_new(Bridge)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bridge.any_instance.stub(:save).and_return(false)
        post :create, {:bridge => { "content" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bridge" do
        bridge = Bridge.create! valid_attributes
        # Assuming there are no other bridges in the database, this
        # specifies that the Bridge created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Bridge.any_instance.should_receive(:update).with({ "content" => "MyString" })
        put :update, {:id => bridge.to_param, :bridge => { "content" => "MyString" }}, valid_session
      end

      it "assigns the requested bridge as @bridge" do
        bridge = Bridge.create! valid_attributes
        put :update, {:id => bridge.to_param, :bridge => valid_attributes}, valid_session
        assigns(:bridge).should eq(bridge)
      end

      it "redirects to the bridge" do
        bridge = Bridge.create! valid_attributes
        put :update, {:id => bridge.to_param, :bridge => valid_attributes}, valid_session
        response.should redirect_to(bridge)
      end
    end

    describe "with invalid params" do
      it "assigns the bridge as @bridge" do
        bridge = Bridge.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bridge.any_instance.stub(:save).and_return(false)
        put :update, {:id => bridge.to_param, :bridge => { "content" => "invalid value" }}, valid_session
        assigns(:bridge).should eq(bridge)
      end

      it "re-renders the 'edit' template" do
        bridge = Bridge.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bridge.any_instance.stub(:save).and_return(false)
        put :update, {:id => bridge.to_param, :bridge => { "content" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bridge" do
      bridge = Bridge.create! valid_attributes
      expect {
        delete :destroy, {:id => bridge.to_param}, valid_session
      }.to change(Bridge, :count).by(-1)
    end

    it "redirects to the bridges list" do
      bridge = Bridge.create! valid_attributes
      delete :destroy, {:id => bridge.to_param}, valid_session
      response.should redirect_to(bridges_url)
    end
  end

end
